BR2_TARGET_GENERIC_HOSTNAME="dhcp-boot"

NETBOX_VENDOR_ID="dhcp-boot"
NETBOX_VENDOR_NAME="DHCP-boot application"
NETBOX_VENDOR_DESC="DHCP-boot Demo - Westermo LXC container"
NETBOX_VENDOR_HOME="https://github.com/westermo/app-demo/"
NETBOX_VENDOR_VERSION="`$BR2_EXTERNAL_NETBOX_PATH/bin/mkversion $BR2_EXTERNAL_DEMO_PATH`"

BR2_PACKAGE_DNSMASQ=y
BR2_PACKAGE_DROPBEAR=y
BR2_PACKAGE_LLDPD=y
BR2_PACKAGE_SOCAT=y
BR2_PACKAGE_TCPDUMP=y
BR2_TARGET_ROOTFS_SQUASHFS=y
BR2_PACKAGE_DHCP_BOOT=y