#!/bin/sh

case "$1" in
	start)
		printf "Starting dhcp-boot: "
		start-stop-daemon -S -x /usr/sbin/dhcp-boot
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping dhcp-boot: "
		start-stop-daemon -K -q -x /usr/sbin/dhcp-boot
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
